image: node:latest

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

pages:
  script:
    - npm install --progress=false
    - ./node_modules/.bin/gulp build
    - rm -rf public
    - mkdir -p public/dist
    - cp -r dist/* public/dist
    - cp index.html public/index.html
  artifacts:
    expire_in: 1 day
    paths:
      - public
  only:
    - main


